# Generated by Django 4.2 on 2025-11-26 08:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KenyaConflictData',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('field1', models.IntegerField(blank=True, null=True)),
                ('event_id_cnty', models.CharField(blank=True, max_length=8000, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('time_precision', models.IntegerField(blank=True, null=True)),
                ('disorder_type', models.CharField(blank=True, max_length=8000, null=True)),
                ('event_type', models.CharField(blank=True, max_length=8000, null=True)),
                ('sub_event_type', models.CharField(blank=True, max_length=8000, null=True)),
                ('actor1', models.CharField(blank=True, max_length=8000, null=True)),
                ('assoc_actor_1', models.CharField(blank=True, max_length=8000, null=True)),
                ('inter1', models.CharField(blank=True, max_length=8000, null=True)),
                ('actor2', models.CharField(blank=True, max_length=8000, null=True)),
                ('assoc_actor_2', models.CharField(blank=True, max_length=8000, null=True)),
                ('inter2', models.CharField(blank=True, max_length=8000, null=True)),
                ('interaction', models.CharField(blank=True, max_length=8000, null=True)),
                ('civilian_targeting', models.CharField(blank=True, max_length=8000, null=True)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=8000, null=True)),
                ('country', models.CharField(blank=True, max_length=8000, null=True)),
                ('admin1', models.CharField(blank=True, max_length=8000, null=True)),
                ('admin2', models.CharField(blank=True, max_length=8000, null=True)),
                ('admin3', models.CharField(blank=True, max_length=8000, null=True)),
                ('location', models.CharField(blank=True, max_length=8000, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('geo_precision', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=8000, null=True)),
                ('source_scale', models.CharField(blank=True, max_length=8000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fatalities', models.IntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=8000, null=True)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('gdb_geomattr_data', models.BinaryField(blank=True, null=True)),
                ('shape', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Kenya Conflict Event',
                'verbose_name_plural': 'Kenya Conflict Events',
                'db_table': 'jack"."kenya_conflict_data',
                'ordering': ['-event_date'],
                'managed': False,
            },
        ),
    ]
